In [2]:
import numpy as np
import pandas as pd

In [3]:
import json
with open('/kaggle/input/convolve-epoch1/train.json','r') as f:
    log=json.load(f)
    
data = pd.DataFrame({'Label':log})

In [4]:
data

                                                       Label
 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005...    normal
 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005...    normal
 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005...    normal
 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005...    normal
 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005...    normal
...                                                      ...
1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005-...  abnormal
1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005-...  abnormal
1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005-...  abnormal
1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005-...  abnormal
1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005-...  abnormal

[4152659 rows x 1 columns]

In [5]:
arr1=np.array(data.index)
arr2=np.array(data['Label'])
train=pd.DataFrame()
train['Log']=arr1
train['Label']=arr2
train

                                                       Log     Label
0         1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...    normal
1         1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...    normal
2         1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...    normal
3         1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...    normal
4         1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...    normal
...                                                    ...       ...
4152654  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal
4152655  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal
4152656  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal
4152657  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal
4152658  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal

[4152659 rows x 2 columns]

In [6]:
train_abnormal = train[train['Label']=='abnormal']
train_abnormal

                                                       Log     Label
4082967  1117869872 2005.06.04 R04-M1-N4-I:J18-U01 2005...  abnormal
4082968  1117869872 2005.06.04 R04-M1-N4-I:J18-U11 2005...  abnormal
4082969  1117869872 2005.06.04 R23-M1-N8-I:J18-U11 2005...  abnormal
4082970  1117869873 2005.06.04 R22-M1-N8-I:J18-U01 2005...  abnormal
4082971  1117869873 2005.06.04 R22-M1-N8-I:J18-U11 2005...  abnormal
...                                                    ...       ...
4152654  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal
4152655  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal
4152656  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal
4152657  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal
4152658  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal

[69692 rows x 2 columns]

In [7]:
train_normal = train[train['Label']=='normal']
train_normal

                                                       Log   Label
0         1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal
1         1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal
2         1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal
3         1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal
4         1117838570 2005.06.03 R02-M1-N0-C:J12-U11 200...  normal
...                                                    ...     ...
4082962   1133448452 2005.12.01 R77-M0-N3-C:J15-U01 200...  normal
4082963   1133448452 2005.12.01 R77-M0-N3-C:J17-U01 200...  normal
4082964   1133448452 2005.12.01 R77-M0-N3-C:J17-U01 200...  normal
4082965   1133448452 2005.12.01 R77-M0-N3-C:J17-U11 200...  normal
4082966   1133448452 2005.12.01 R77-M0-N3-C:J17-U11 200...  normal

[4082967 rows x 2 columns]

In [8]:
train_normal_downsampled = train_normal.sample(2*train_abnormal.shape[0])
train_normal_downsampled.shape

(139384, 2)

In [9]:
train = pd.concat([train_normal_downsampled,train_abnormal])
train

                                                       Log     Label
2412296   1122166584 2005.07.23 R14-M0-ND-C:J04-U11 200...    normal
2559459   1122547707 2005.07.28 R34-M1-N6-C:J10-U01 200...    normal
3644237   1131127205 2005.11.04 R62-M0-N7-C:J13-U01 200...    normal
2248850   1121905311 2005.07.20 R20-M1-N6-C:J06-U11 200...    normal
3542329   1131061784 2005.11.03 R64-M0-NA-C:J03-U11 200...    normal
...                                                    ...       ...
4152654  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal
4152655  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal
4152656  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal
4152657  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal
4152658  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal

[209076 rows x 2 columns]

In [10]:
train.reset_index(inplace=True)
train

          index                                                Log     Label
0       2412296   1122166584 2005.07.23 R14-M0-ND-C:J04-U11 200...    normal
1       2559459   1122547707 2005.07.28 R34-M1-N6-C:J10-U01 200...    normal
2       3644237   1131127205 2005.11.04 R62-M0-N7-C:J13-U01 200...    normal
3       2248850   1121905311 2005.07.20 R20-M1-N6-C:J06-U11 200...    normal
4       3542329   1131061784 2005.11.03 R64-M0-NA-C:J03-U11 200...    normal
...         ...                                                ...       ...
209071  4152654  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal
209072  4152655  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal
209073  4152656  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal
209074  4152657  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal
209075  4152658  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal

[209076 rows x 3 columns]

In [11]:
train.drop('index',axis=1, inplace=True)
train

                                                      Log     Label
0        1122166584 2005.07.23 R14-M0-ND-C:J04-U11 200...    normal
1        1122547707 2005.07.28 R34-M1-N6-C:J10-U01 200...    normal
2        1131127205 2005.11.04 R62-M0-N7-C:J13-U01 200...    normal
3        1121905311 2005.07.20 R20-M1-N6-C:J06-U11 200...    normal
4        1131061784 2005.11.03 R64-M0-NA-C:J03-U11 200...    normal
...                                                   ...       ...
209071  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal
209072  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal
209073  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal
209074  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal
209075  1118545530 2005.06.11 R30-M0-N9-C:J16-U01 2005...  abnormal

[209076 rows x 2 columns]

In [12]:
train['Label'].value_counts()

normal      139384
abnormal     69692
Name: Label, dtype: int64

In [13]:
import random
for i in range(5):
    index = random.randint(0,len(train['Log']))
    print(str(index)+'th Log is: '+train['Log'][index])

187738th Log is: 1118542145 2005.06.11 R30-M0-N9-C:J16-U01 2005-06-11-19.09.05.175611 R30-M0-N9-C:J16-U01 RAS KERNEL FATAL data TLB error interrupt
129324th Log is:  1121312122 2005.07.13 R35-M1-N2-C:J13-U01 2005-07-13-20.35.22.981622 R35-M1-N2-C:J13-U01 RAS KERNEL INFO generating core.26853

169727th Log is: 1118539417 2005.06.11 R30-M0-N9-C:J16-U01 2005-06-11-18.23.37.744792 R30-M0-N9-C:J16-U01 RAS KERNEL FATAL data TLB error interrupt
112544th Log is:  1121252336 2005.07.13 R34-M0-N5-C:J03-U11 2005-07-13-03.58.56.139550 R34-M0-N5-C:J03-U11 RAS KERNEL INFO 114409496 double-hummer alignment exceptions

109702th Log is:  1119571783 2005.06.23 R22-M1-N8-C:J08-U01 2005-06-23-17.09.43.664187 R22-M1-N8-C:J08-U01 RAS KERNEL INFO 3091200 double-hummer alignment exceptions

In [14]:
pip! install nltk

ERROR: unknown command "!"
Note: you may need to restart the kernel to use updated packages.

In [15]:
#now we will clean n data a bit
import nltk
import re
nltk.download('stopwords')
nltk.download('wordnet')
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [16]:
wordnet=WordNetLemmatizer()

In [17]:
for i,sentence in enumerate(train['Log']):
    new_sentence = re.sub('[^a-zA-Z]', ' ', sentence)
    train['Log'][i]=new_sentence

In [18]:
for i in range(5):
    index = random.randint(0,len(train['Log']))
    print(str(index)+'th Log is: '+train['Log'][index])

77368th Log is:                        R   M  NE C J   U                              R   M  NE C J   U   RAS KERNEL INFO iar       b  dear    b c c
36776th Log is:                        R   M  NA C J   U                              R   M  NA C J   U   RAS KERNEL INFO CE sym     at  x b  b     mask  x
87986th Log is:                        R   M  N  I J   U                              R   M  N  I J   U   RAS APP FATAL ciod  Error loading  home yates SWL tests BGL  k SWL tests develop MPI PERF IMB perf tests IMB MPI     B  invalid or missing program image  No such file or directory
22290th Log is:                        R   M  N  I J   U                              R   M  N  I J   U   RAS KERNEL INFO ciod  generated     core files for program  home spelce  HPCC IBM Urgent COP   K vnm rts
47355th Log is:                        R   M  N  I J   U                              R   M  N  I J   U   RAS KERNEL INFO ciod  Received signal     code    errno    address  x      f

In [19]:
import nltk
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...

True

In [20]:
corpus = []
for i in range(len(train['Log'])):
    review = train['Log'][i].lower()
    review = review.split()
    review = [wordnet.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [21]:
len(corpus)==len(train['Log'])

True

In [22]:
#Let's checkout some lemmatized texts
for i in range(5):
    index = random.randint(0,len(train['Log']))
    print(str(index)+'th Log is: '+corpus[index])

63995th Log is: r nb c j u r nb c j u ra kernel info generating core
121468th Log is: r n c j u r n c j u ra kernel info torus receiver x input pipe error dcr x ec detected corrected
23140th Log is: r nb c j u r nb c j u ra kernel fatal ce ffffffff
168050th Log is: r n c j u r n c j u ra kernel fatal data tlb error interrupt
151946th Log is: r n c j u r n c j u ra kernel fatal data tlb error interrupt

In [23]:
#let's vectorize them
from sklearn.feature_extraction.text import TfidfVectorizer

In [65]:
train_Lemmatized=pd.DataFrame(corpus,columns={'Log'})
train_Lemmatized

                                                      Log
0       r nd c j u r nd c j u ra kernel info floating ...
1       r n c j u r n c j u ra kernel info ce sym x ac...
2       r n c j u r n c j u ra kernel info iar dear f e c
3       r n c j u r n c j u ra kernel info floating po...
4       r na c j u r na c j u ra kernel info iar dear e c
...                                                   ...
209071  r n c j u r n c j u ra kernel fatal data tlb e...
209072  r n c j u r n c j u ra kernel fatal data tlb e...
209073  r n c j u r n c j u ra kernel fatal data tlb e...
209074  r n c j u r n c j u ra kernel fatal data tlb e...
209075  r n c j u r n c j u ra kernel fatal data tlb e...

[209076 rows x 1 columns]

In [68]:
train_Lemmatized.to_csv('/kaggle/working/train_Lemmatized.csv')

In [24]:
transformer =TfidfVectorizer(max_features=500)
X = transformer.fit_transform(corpus).toarray()

In [62]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [25]:
X.shape

(209076, 500)

In [26]:
np.unique(X[0])

array([0.        , 0.0883989 , 0.09273471, 0.13682724, 0.28931305,
       0.29403005, 0.3503527 , 0.35442054, 0.73915328])

In [27]:
Y = train['Label'].apply(lambda x: 1 if x=='normal' else 0)
Y

0         1
1         1
2         1
3         1
4         1
         ..
209071    0
209072    0
209073    0
209074    0
209075    0
Name: Label, Length: 209076, dtype: int64

In [28]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
model.fit(X,Y)
model.score(X,Y)

0.9999426046031108

In [29]:
y_predicted = model.predict(X)
y_predicted

array([1, 1, 1, ..., 0, 0, 0])

In [30]:
from sklearn.metrics import confusion_matrix, classification_report

cm = confusion_matrix(Y, y_predicted)
cm

array([[ 69686,      6],
       [     6, 139378]])

In [31]:
from sklearn.ensemble import RandomForestClassifier
model_rf = RandomForestClassifier()
model_rf.fit(X,Y)
model_rf.score(X,Y)

1.0

In [32]:
y_predicted = model_rf.predict(X)
y_predicted

array([1, 1, 1, ..., 0, 0, 0])

In [33]:
from sklearn.metrics import confusion_matrix, classification_report

cm = confusion_matrix(Y, y_predicted)
cm

array([[ 69692,      0],
       [     0, 139384]])

Now that's some impressive prediction we got

In [34]:
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
import pickle

In [35]:
filename = '/kaggle/working/RFClassifier_model.sav'
pickle.dump(model_rf, open(filename, 'wb'))

In [36]:
filename = '/kaggle/working/KNNClassifier_model.sav'
pickle.dump(model, open(filename, 'wb'))

In [37]:
test = pd.read_csv('/kaggle/input/convolve-epoch1/test.csv')
test

            ID                                                Log
0            0   1124336301 2005.08.17 R13-M1-N8-C:J12-U01 200...
1            1   1118553175 2005.06.11 R30-M0-N9-C:J16-U01 200...
2            2   1118536033 2005.06.11 R30-M0-N9-C:J16-U01 200...
3            3   1117992566 2005.06.05 R30-M1-N6-C:J03-U11 200...
4            4   1118538965 2005.06.11 R30-M0-N9-C:J16-U01 200...
...        ...                                                ...
595295  595295   1118768234 2005.06.14 R20-M0-NA-C:J17-U11 200...
595296  595296   1118370947 2005.06.09 R15-M0-NA-C:J02-U01 200...
595297  595297   1118540242 2005.06.11 R30-M0-N9-C:J16-U01 200...
595298  595298   1118538947 2005.06.11 R30-M0-N9-C:J16-U01 200...
595299  595299   1118165805 2005.06.07 R23-M1-N5-C:J16-U11 200...

[595300 rows x 2 columns]

In [39]:
test.columns

Index(['ID', ' Log'], dtype='object')

In [40]:
for i,sentence in enumerate(test[' Log']):
    new_sentence = re.sub('[^a-zA-Z]', ' ', sentence)
    train['Log'][i]=new_sentence

In [41]:
test_corpus = []
for i in range(len(test[' Log'])):
    review = test[' Log'][i].lower()
    review = review.split()
    review = [wordnet.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    test_corpus.append(review)

In [42]:
len(test_corpus)==len(test[' Log'])

True

In [43]:
X_test = transformer.transform(test_corpus).toarray()
X_test.shape

(595300, 500)

In [44]:
prediction_rf=model_rf.predict(X_test)
np.unique(prediction_rf,return_counts=True)

(array([0, 1]), array([170595, 424705]))

In [45]:
prediction_knn=model.predict(X_test)
np.unique(prediction_knn,return_counts=True)

(array([0, 1]), array([234075, 361225]))

In [46]:
ss = pd.read_csv('/kaggle/input/convolve-epoch1/sample_submission.csv')
ss.drop(' Label',axis=1,inplace=True)

In [57]:
np.unique(prediction_rf, return_counts=True)

(array([0, 1]), array([170595, 424705]))

In [53]:
ss

            ID     Label
0            0    normal
1            1  abnormal
2            2  abnormal
3            3    normal
4            4  abnormal
...        ...       ...
595295  595295    normal
595296  595296    normal
595297  595297  abnormal
595298  595298  abnormal
595299  595299    normal

[595300 rows x 2 columns]

In [58]:
submission_rf=ss.copy()
submission_rf[' Label']=prediction_rf
submission_rf[' Label'] = submission_rf[' Label'].apply(lambda x: 'normal' if x==1 else 'abnormal')

In [59]:
submission_rf[' Label'].value_counts()

normal      424705
abnormal    170595
Name:  Label, dtype: int64

In [61]:
submission_rf.to_csv('/kaggle/working/submission_RF.csv',index=False)
print('Done!!')

Done!!

In [48]:
submission_knn=ss
submission_knn[' Label']=prediction_knn
submission_knn[' Label'] = submission_knn[' Label'].apply(lambda x: 'normal' if x==1 else 'abnormal')

In [49]:
print(submission_rf,submission_knn)

            ID     Label
0            0    normal
1            1  abnormal
2            2  abnormal
3            3    normal
4            4  abnormal
...        ...       ...
595295  595295    normal
595296  595296    normal
595297  595297  abnormal
595298  595298  abnormal
595299  595299    normal

[595300 rows x 2 columns]             ID     Label
0            0    normal
1            1  abnormal
2            2  abnormal
3            3    normal
4            4  abnormal
...        ...       ...
595295  595295    normal
595296  595296    normal
595297  595297  abnormal
595298  595298  abnormal
595299  595299    normal

[595300 rows x 2 columns]

In [51]:
# submission_rf.to_csv('submission_rf.csv',index=False)
# submission_knn.to_csv('submission_knn.csv',index=False)
# print('Submissions saved!')

Submissions saved!

In [52]:
submission_knn.to_csv('/kaggle/working/submission_knn.csv',index=False)
print('Submissions saved!')

Submissions saved!

In [54]:
s_knn=pd.read_csv('/kaggle/working/submission_knn.csv')
s_rf = pd.read_csv('/kaggle/working/submission_rf.csv')

In [55]:
s_knn[' Label'].value_counts()

normal      361225
abnormal    234075
Name:  Label, dtype: int64

In [56]:
s_rf[' Label'].value_counts()

normal      361225
abnormal    234075
Name:  Label, dtype: int64